TESTING: Found solution for the error that was thrown when querying the Gurobi model. The reason is that, if the model does not contain a constraint then the list of constraints is empty and the method model.getConstrByName(name) will throw this error. I also realized, that I need to run `model.update()` after adding a constraint, so that they are registered in the list of constraints and hence the call to model.getConstrByName(name) does not still fail _after_ adding constraints (i.e. the function model.getConstrs() is not empty anymore).
```
java.lang.RuntimeException: gurobi.GRBException: No constraint names available to index
	at com.jug.lp.AbstractAssignment.constraintExistsWithName(AbstractAssignment.java:277)
	at com.jug.lp.AbstractAssignment.addConstraint(AbstractAssignment.java:252)
	at com.jug.lp.AbstractAssignment.addGroundUntruthConstraint(AbstractAssignment.java:248)
	at com.jug.lp.AbstractAssignment.setGroundUntruth(AbstractAssignment.java:220)
	at com.jug.lp.GrowthlaneTrackingILP.addMappingAssignments(GrowthlaneTrackingILP.java:637)
	at com.jug.lp.GrowthlaneTrackingILP.createAssignmentsForTimeStep(GrowthlaneTrackingILP.java:533)
	at com.jug.lp.GrowthlaneTrackingILP.createAssignments(GrowthlaneTrackingILP.java:486)
	at com.jug.lp.GrowthlaneTrackingILP.buildILP(GrowthlaneTrackingILP.java:220)
	at com.jug.Growthlane.generateILP(Growthlane.java:136)
	at com.jug.datahandling.GlDataLoader.generateILPs(GlDataLoader.java:127)
	at com.jug.MoMA.main(MoMA.java:219)
	at com.jug.exploration.ExplorationTestHelpers.startMoma(ExplorationTestHelpers.java:69)
	at com.jug.feature.Feature__20220919_use_fluorescence_signal_to_select_valid_components.run_trackonly(Feature__20220919_use_fluorescence_signal_to_select_valid_components.java:49)
	at com.jug.feature.Feature__20220919_use_fluorescence_signal_to_select_valid_components.main(Feature__20220919_use_fluorescence_signal_to_select_valid_components.java:28)
Caused by: gurobi.GRBException: No constraint names available to index
	at gurobi.GRBModel.getConstrByName(GRBModel.java:617)
	at com.jug.lp.GRBModel.GRBModelAdapter.getConstrByName(GRBModelAdapter.java:17)
	at com.jug.lp.AbstractAssignment.constraintExistsWithName(AbstractAssignment.java:275)
	... 13 more
```